# Generated by Django 5.1.4 on 2025-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('residence', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=15)),
                ('patient_consulting', models.CharField(max_length=255)),
                ('patient_relationship', models.CharField(max_length=255)),
                ('consultation_date', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('is_payment_verified', models.BooleanField(default=False)),
                ('zoom_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
