# Generated by Django 5.1.4 on 2025-01-17 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
