# Generated by Django 5.1.4 on 2025-02-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationbooking',
            name='is_payment_verified',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
